backend:
  name: git-gateway
  branch: Netlify # Branch to update (optional; defaults to master)
media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "stylists" # Used in routes, e.g., /admin/collections/blog
    label: "Stylists" # Used in the UI
    folder: "_stylists" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Phone", name: "phone", widget: "string"}
      - {label: "E-Mail", name: "email", widget: "string"}
      - {label: "Mini Bio", name: "mini-bio", widget: "markdown"}
      - {label: "Bio", name: "bio", widget: "markdown"}
      - {label: "Prices", name: "prices", widget: "list"}